#!/bin/bash
#
# Usage: generate_shortcuts 
# 

# Uncomment for Strict mode, more info at:
# http://redsymbol.net/articles/unofficial-bash-strict-mode
# set -euo pipefail
# IFS=$'\n\t'

existingCommands=$(echo $(compgen -c) $(compgen -A function) | tr ' ' '\n' | sort | uniq -u | tr '\n' ' ')
./parse_rc.py "$existingCommands" > ~/.standardshortcuts


