#!/bin/bash
#
# Usage: uninstall 
#

# Stops execution if any command fails.
set -eo pipefail

main() {
    rm -f ~/.standard_aliases/standard_aliases
    rm -f ~/.standard_aliases/standard_shortcuts
    rmdir ~/.standard_aliases 2>/dev/null
}

main "$@"
