#!/bin/bash
#
# Usage: generate_shortcuts 
# Runs parse-rc script, that parses ~/.standardrc and generates
# new ~/.standard_aliases/shortcuts.

# Stops execution if any command fails.
set -eo pipefail

main() {
    scriptsDir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
    existingCommands=$(
        echo $(compgen -c) $(compgen -A function) \
            | tr ' ' '\n' \
            | sort \
            | uniq -u \
            | tr '\n' ' ')
    existingCompletions=$(. /usr/share/bash-completion/bash_completion; complete)
    shortcuts=$(
        "$scriptsDir"/parse-rc.py \
            "$existingCommands" \
            "$existingCompletions")
#    if [[ $? != 0 ]]; then
#        touch "$HOME"/.standard_rc
#        echo -n "Standard aliases: There is a problem in parse-rc.py " >&2
#        echo -n "script, so aliases were not loaded." >&2
#        exit 1
#    fi
    echo "$shortcuts" > ~/.standard_aliases/shortcuts
}

main "$@"
